In [1]:
import pandas as pd

In [2]:
no_host_filt = pd.read_csv('../data/Microbiome/5XFAD_no_host_filt_counts.csv', index_col=0)
host_filt = pd.read_csv('../data/Microbiome/5XFAD_host_filt_counts.csv', index_col=0)

In [3]:
no_host_filt.head()

                                  old_frequency
sample_id
14957.MOUSE125.CAGE185.MSPFWT.S5       17007489
14957.MOUSE124.CAGE185.MSPFWT.S5        9125207
14957.MOUSE126.CAGE185.MSPFWT.S5        7659482
14957.CAGE189.MSPFHET.L2.1              7524008
14957.CAGE144.MSPFWT.L2.1               7214183

In [4]:
comp = pd.merge(no_host_filt, host_filt, left_index=True, right_index=True)
comp.head()

                                  old_frequency  new_frequency
sample_id
14957.MOUSE125.CAGE185.MSPFWT.S5       17007489       13658712
14957.MOUSE124.CAGE185.MSPFWT.S5        9125207        8234925
14957.MOUSE126.CAGE185.MSPFWT.S5        7659482        7396125
14957.CAGE189.MSPFHET.L2.1              7524008        6815905
14957.CAGE144.MSPFWT.L2.1               7214183        6870661

In [13]:
comp.shape

(288, 4)

In [5]:
comp['differences'] = comp['old_frequency']-comp['new_frequency']

In [6]:
comp.head()

                                  old_frequency  new_frequency  differences
sample_id
14957.MOUSE125.CAGE185.MSPFWT.S5       17007489       13658712      3348777
14957.MOUSE124.CAGE185.MSPFWT.S5        9125207        8234925       890282
14957.MOUSE126.CAGE185.MSPFWT.S5        7659482        7396125       263357
14957.CAGE189.MSPFHET.L2.1              7524008        6815905       708103
14957.CAGE144.MSPFWT.L2.1               7214183        6870661       343522

In [7]:
comp['percent_old'] = comp['differences']/comp['old_frequency']

In [8]:
comp.head()

,old_frequency,new_frequency,differences,percent_old
sample_id,,,,
14957.MOUSE125.CAGE185.MSPFWT.S5,17007489,13658712,3348777,0.196900
14957.MOUSE124.CAGE185.MSPFWT.S5,9125207,8234925,890282,0.097563
14957.MOUSE126.CAGE185.MSPFWT.S5,7659482,7396125,263357,0.034383
14957.CAGE189.MSPFHET.L2.1,7524008,6815905,708103,0.094112
14957.CAGE144.MSPFWT.L2.1,7214183,6870661,343522,0.047618

In [9]:
comp.tail()

                      old_frequency  new_frequency  differences  percent_old
sample_id
14957.BLANK.FAD.1.1D           3084           3045           39     0.012646
14957.BLANK.FAD.3.8B           2602           2602            0     0.000000
14957.BLANK.FAD.1.1H           2184           2182            2     0.000916
14957.BLANK.FAD.3.7C           2183           2183            0     0.000000
14957.BLANK.FAD.3.7B           1558           1558            0     0.000000

In [10]:
comp[comp['percent_old']>0.1]

,old_frequency,new_frequency,differences,percent_old
sample_id,,,,
14957.MOUSE125.CAGE185.MSPFWT.S5,17007489,13658712,3348777,0.196900
14957.MOUSE26.CAGE79.MSPFWT.S8,5782183,4584689,1197494,0.207101
14957.CAGE142.MSPFWT.L2.1,5549115,3887186,1661929,0.299494
14957.MOUSE148.CAGE147.FSPFHET.S8,5248955,6428,5242527,0.998775
14957.CAGE147.FSPFHET.L7.2,4978269,4176164,802105,0.161121
...,...,...,...,...
14957.BLANK.FAD.2.2F,400367,338770,61597,0.153851
14957.BLANK.FAD.3.9F,219775,134710,85065,0.387055
14957.BLANK.FAD.3.9D,112521,96191,16330,0.145128
14957.BLANK.FAD.3.7E,87149,69871,17278,0.198258
14957.BLANK.FAD.3.10B,22120,15579,6541,0.295705

In [12]:
comp.sort_values(by='percent_old', ascending=False)

,old_frequency,new_frequency,differences,percent_old
sample_id,,,,
14957.MOUSE148.CAGE147.FSPFHET.S8,5248955,6428,5242527,0.998775
14957.MOUSE149.CAGE147.FSPFHET.S8,4047620,5218,4042402,0.998711
14957.CAGE148.FSPFHET.L5.2,4464848,1370149,3094699,0.693125
14957.CAGE150.FSPFHET.L5.2,3223493,1668393,1555100,0.482427
14957.CAGE78.MSPFHET.L3.2,1785778,963783,821995,0.460301
...,...,...,...,...
14957.BLANK.FAD.3.9A,10755,10755,0,0.000000
14957.BLANK.FAD.3.7H,11593,11593,0,0.000000
14957.BLANK.FAD.3.7G,13627,13627,0,0.000000
14957.BLANK.FAD.3.3F,19032,19032,0,0.000000
14957.BLANK.FAD.3.7B,1558,1558,0,0.000000

In [14]:
comp[comp['percent_old']>0.5]

,old_frequency,new_frequency,differences,percent_old
sample_id,,,,
14957.MOUSE148.CAGE147.FSPFHET.S8,5248955,6428,5242527,0.998775
14957.CAGE148.FSPFHET.L5.2,4464848,1370149,3094699,0.693125
14957.MOUSE149.CAGE147.FSPFHET.S8,4047620,5218,4042402,0.998711